-- 35
select concat(s.first_name, ' ', s.last_name) as student_name
from enrollments e
join students s
on e.student_id = s.student_id
group by s.first_name, s.last_name, e.student_id
having count(e.course_id) > 
	(
		select avg(course_count)
		from (
			select count(enrollment_id) as course_count
			from enrollments
			group by student_id
		) as avg_student_course_count
	);

-- 36
select c.course_id, c.course_name
from courses c
where not exists (
	select 1
	from enrollments e
	where e.course_id = c.course_id
	and (e.grade != 'A' or e.grade IS NULL)
)

-- 37


CREATE TABLE students (
	id int generated by default as identity primary key,
	name varchar(50),
	semester int check (semester >= 1 AND semester <= 8),
	foreign key int department_id references department(id)
)
